<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/txs/txs.proto

namespace GPBMetadata\V2\Txs;

class Txs
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\V2\Basis\Basis::initOnce();
        $pool->internalAddGeneratedFile(
            '
…
v2/txs/txs.prototxs_v2v2/basis/basis.proto"µ
GetTxsRecordsRequest
imp_uid (	
merchant_uid (	
paid_by (	
status (	
page (
sorting (	
limit (
pg_provider (	

pay_method	 (	

buyer_name
 (	
	buyer_tel (	
buyer_email (	
start (	
end (	
sandbox (
output_format (	"Y
GetTxsRecordsReponse
code (
message (	"
response (2.basis_v2.UnitTx2}

TxsServiceo
GetTxsRecordService.txs_v2.GetTxsRecordsRequest.txs_v2.GetTxsRecordsReponse"‚Óä“/api/payments/v2/txsB9Z.github.com/iamport/interface/gen_src/go/v2/txsªV2.Txsbproto3'
        , true);

        static::$is_initialized = true;
    }
}

