<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/txs/txs.proto

namespace Txs_v2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>txs_v2.GetTxsRecordsReponse</code>
 */
class GetTxsRecordsReponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     */
    protected $code = 0;
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>repeated .basis_v2.UnitTx response = 3;</code>
     */
    private $response;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $code
     *     @type string $message
     *     @type \Basis_v2\UnitTx[]|\Google\Protobuf\Internal\RepeatedField $response
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2\Txs\Txs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .basis_v2.UnitTx response = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>repeated .basis_v2.UnitTx response = 3;</code>
     * @param \Basis_v2\UnitTx[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResponse($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basis_v2\UnitTx::class);
        $this->response = $arr;

        return $this;
    }

}

