<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custompay/v1/basic/basic.proto

namespace GPBMetadata\Custompay\V1\Basic;

class Basic
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab7010a1e637573746f6d7061792f76312f62617369632f62617369632e70726f746f120f62617369635f637573746f6d70617922290a08526573706f6e7365120c0a04636f6465180120012805120f0a076d65737361676518022001280942515a3a6769746875622e636f6d2f69616d706f72742f696e746572666163652f67656e5f7372632f676f2f637573746f6d7061792f76312f6261736963aa0212437573746f6d7061792e56312e4261736963620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

