<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/authenticate/token.proto

namespace GPBMetadata\V1\Authenticate;

class Token
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ç
v1/authenticate/token.protoauthenticate">
Token
access_token (	
now (

expired_at ("3
TokenRequest
imp_key (	

imp_secret (	"U
TokenResponse
code (
message (	%
response (2.authenticate.Token2y
TokenServicei
TokenRPC.authenticate.TokenRequest.authenticate.TokenResponse"$‚Óä“"/api/payments/v1/gettoken:*BKZ7github.com/iamport/interface/gen_src/go/v1/authenticateªV1.Authenticatebproto3'
        , true);

        static::$is_initialized = true;
    }
}

