<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/subscribe/subscribe.proto

namespace Subscribe;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>subscribe.UnscheduelPaymentRequest</code>
 */
class UnscheduelPaymentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string customer_uid = 1;</code>
     */
    protected $customer_uid = '';
    /**
     * Generated from protobuf field <code>repeated string merchant_uid = 2;</code>
     */
    private $merchant_uid;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $customer_uid
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $merchant_uid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V1\Subscribe\Subscribe::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string customer_uid = 1;</code>
     * @return string
     */
    public function getCustomerUid()
    {
        return $this->customer_uid;
    }

    /**
     * Generated from protobuf field <code>string customer_uid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string merchant_uid = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMerchantUid()
    {
        return $this->merchant_uid;
    }

    /**
     * Generated from protobuf field <code>repeated string merchant_uid = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMerchantUid($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->merchant_uid = $arr;

        return $this;
    }

}

