<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payment/payment.proto

namespace Payment;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>payment.PaymentBalanceHistory</code>
 */
class PaymentBalanceHistory extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.payment.PaymentBalanceDetail cash_receipt = 1;</code>
     */
    protected $cash_receipt = null;
    /**
     * Generated from protobuf field <code>.payment.PaymentBalanceDetail primary = 2;</code>
     */
    protected $primary = null;
    /**
     * Generated from protobuf field <code>.payment.PaymentBalanceDetail secondary = 3;</code>
     */
    protected $secondary = null;
    /**
     * Generated from protobuf field <code>.payment.PaymentBalanceDetail discount = 4;</code>
     */
    protected $discount = null;
    /**
     * Generated from protobuf field <code>int32 created = 5;</code>
     */
    protected $created = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Payment\PaymentBalanceDetail $cash_receipt
     *     @type \Payment\PaymentBalanceDetail $primary
     *     @type \Payment\PaymentBalanceDetail $secondary
     *     @type \Payment\PaymentBalanceDetail $discount
     *     @type int $created
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V1\Payment\Payment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.payment.PaymentBalanceDetail cash_receipt = 1;</code>
     * @return \Payment\PaymentBalanceDetail|null
     */
    public function getCashReceipt()
    {
        return $this->cash_receipt;
    }

    public function hasCashReceipt()
    {
        return isset($this->cash_receipt);
    }

    public function clearCashReceipt()
    {
        unset($this->cash_receipt);
    }

    /**
     * Generated from protobuf field <code>.payment.PaymentBalanceDetail cash_receipt = 1;</code>
     * @param \Payment\PaymentBalanceDetail $var
     * @return $this
     */
    public function setCashReceipt($var)
    {
        GPBUtil::checkMessage($var, \Payment\PaymentBalanceDetail::class);
        $this->cash_receipt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.payment.PaymentBalanceDetail primary = 2;</code>
     * @return \Payment\PaymentBalanceDetail|null
     */
    public function getPrimary()
    {
        return $this->primary;
    }

    public function hasPrimary()
    {
        return isset($this->primary);
    }

    public function clearPrimary()
    {
        unset($this->primary);
    }

    /**
     * Generated from protobuf field <code>.payment.PaymentBalanceDetail primary = 2;</code>
     * @param \Payment\PaymentBalanceDetail $var
     * @return $this
     */
    public function setPrimary($var)
    {
        GPBUtil::checkMessage($var, \Payment\PaymentBalanceDetail::class);
        $this->primary = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.payment.PaymentBalanceDetail secondary = 3;</code>
     * @return \Payment\PaymentBalanceDetail|null
     */
    public function getSecondary()
    {
        return $this->secondary;
    }

    public function hasSecondary()
    {
        return isset($this->secondary);
    }

    public function clearSecondary()
    {
        unset($this->secondary);
    }

    /**
     * Generated from protobuf field <code>.payment.PaymentBalanceDetail secondary = 3;</code>
     * @param \Payment\PaymentBalanceDetail $var
     * @return $this
     */
    public function setSecondary($var)
    {
        GPBUtil::checkMessage($var, \Payment\PaymentBalanceDetail::class);
        $this->secondary = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.payment.PaymentBalanceDetail discount = 4;</code>
     * @return \Payment\PaymentBalanceDetail|null
     */
    public function getDiscount()
    {
        return $this->discount;
    }

    public function hasDiscount()
    {
        return isset($this->discount);
    }

    public function clearDiscount()
    {
        unset($this->discount);
    }

    /**
     * Generated from protobuf field <code>.payment.PaymentBalanceDetail discount = 4;</code>
     * @param \Payment\PaymentBalanceDetail $var
     * @return $this
     */
    public function setDiscount($var)
    {
        GPBUtil::checkMessage($var, \Payment\PaymentBalanceDetail::class);
        $this->discount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 created = 5;</code>
     * @return int
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Generated from protobuf field <code>int32 created = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkInt32($var);
        $this->created = $var;

        return $this;
    }

}

