# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/escrow/escrow.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("v1/escrow/escrow.proto", :syntax => :proto3) do
    add_message "escrow.Info" do
      optional :name, :string, 1
      optional :tel, :string, 2
      optional :addr, :string, 3
      optional :postcode, :string, 4
    end
    add_message "escrow.Logis" do
      optional :company, :string, 1
      optional :invoice, :string, 2
      optional :sent_at, :int32, 3
      optional :applied_at, :int32, 4
    end
    add_message "escrow.EscrowRequest" do
      optional :imp_uid, :string, 1
      optional :sender, :message, 2, "escrow.Info"
      optional :receiver, :message, 3, "escrow.Info"
      optional :logis, :message, 4, "escrow.Logis"
    end
    add_message "escrow.EscrowResponse" do
      optional :code, :int32, 1
      optional :message, :string, 2
      optional :response, :message, 3, "escrow.Logis"
    end
  end
end

module Escrow
  Info = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("escrow.Info").msgclass
  Logis = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("escrow.Logis").msgclass
  EscrowRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("escrow.EscrowRequest").msgclass
  EscrowResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("escrow.EscrowResponse").msgclass
end
