<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/basis/basis.proto

namespace Basis_v2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>basis_v2.UnitTx</code>
 */
class UnitTx extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string amount = 1;</code>
     */
    protected $amount = '';
    /**
     * Generated from protobuf field <code>string apply_num = 2;</code>
     */
    protected $apply_num = '';
    /**
     * Generated from protobuf field <code>int32 bank_code = 3;</code>
     */
    protected $bank_code = 0;
    /**
     * Generated from protobuf field <code>string bank_name = 4;</code>
     */
    protected $bank_name = '';
    /**
     * Generated from protobuf field <code>string buyer_addr = 5;</code>
     */
    protected $buyer_addr = '';
    /**
     * Generated from protobuf field <code>string buyer_email = 6;</code>
     */
    protected $buyer_email = '';
    /**
     * Generated from protobuf field <code>string buyer_name = 7;</code>
     */
    protected $buyer_name = '';
    /**
     * Generated from protobuf field <code>string buyer_postcode = 8;</code>
     */
    protected $buyer_postcode = '';
    /**
     * Generated from protobuf field <code>string buyer_tel = 9;</code>
     */
    protected $buyer_tel = '';
    /**
     * Generated from protobuf field <code>string cancel_amount = 10;</code>
     */
    protected $cancel_amount = '';
    /**
     * Generated from protobuf field <code>repeated .basis_v2.CancelHistory cancel_history = 11;</code>
     */
    private $cancel_history;
    /**
     * Generated from protobuf field <code>string cancel_reason = 12;</code>
     */
    protected $cancel_reason = '';
    /**
     * Generated from protobuf field <code>repeated string cancel_receipt_urls = 13;</code>
     */
    private $cancel_receipt_urls;
    /**
     * Generated from protobuf field <code>int32 cancelled_at = 14;</code>
     */
    protected $cancelled_at = 0;
    /**
     * Generated from protobuf field <code>string card_code = 15;</code>
     */
    protected $card_code = '';
    /**
     * Generated from protobuf field <code>string bin_number = 16;</code>
     */
    protected $bin_number = '';
    /**
     * card issuer
     *
     * Generated from protobuf field <code>string card_name = 17;</code>
     */
    protected $card_name = '';
    /**
     * Generated from protobuf field <code>string card_receipe_name = 18;</code>
     */
    protected $card_receipe_name = '';
    /**
     * Generated from protobuf field <code>string card_owner_type = 19;</code>
     */
    protected $card_owner_type = '';
    /**
     * Generated from protobuf field <code>string card_brand = 20;</code>
     */
    protected $card_brand = '';
    /**
     * Generated from protobuf field <code>string card_credit_type = 21;</code>
     */
    protected $card_credit_type = '';
    /**
     * Generated from protobuf field <code>string card_number = 22;</code>
     */
    protected $card_number = '';
    /**
     * Generated from protobuf field <code>int32 card_installment = 23;</code>
     */
    protected $card_installment = 0;
    /**
     * Generated from protobuf field <code>int32 card_type = 24;</code>
     */
    protected $card_type = 0;
    /**
     * Generated from protobuf field <code>bool cash_receipt_issued = 25;</code>
     */
    protected $cash_receipt_issued = false;
    /**
     * Generated from protobuf field <code>string channel = 26;</code>
     */
    protected $channel = '';
    /**
     * Generated from protobuf field <code>string currency = 27;</code>
     */
    protected $currency = '';
    /**
     * Generated from protobuf field <code>string custom_data = 28;</code>
     */
    protected $custom_data = '';
    /**
     * Generated from protobuf field <code>string card_uid = 29;</code>
     */
    protected $card_uid = '';
    /**
     * Generated from protobuf field <code>string customer_uid_usage = 30;</code>
     */
    protected $customer_uid_usage = '';
    /**
     * Generated from protobuf field <code>bool escrow = 31;</code>
     */
    protected $escrow = false;
    /**
     * Generated from protobuf field <code>string fail_reason = 32;</code>
     */
    protected $fail_reason = '';
    /**
     * Generated from protobuf field <code>int32 failed_at = 33;</code>
     */
    protected $failed_at = 0;
    /**
     * Generated from protobuf field <code>string imp_uid = 34;</code>
     */
    protected $imp_uid = '';
    /**
     * Generated from protobuf field <code>string merchant_uid = 35;</code>
     */
    protected $merchant_uid = '';
    /**
     * Generated from protobuf field <code>string order_name = 36;</code>
     */
    protected $order_name = '';
    /**
     * Generated from protobuf field <code>int32 paid_at = 37;</code>
     */
    protected $paid_at = 0;
    /**
     * Generated from protobuf field <code>string pay_method = 38;</code>
     */
    protected $pay_method = '';
    /**
     * Generated from protobuf field <code>string pg_id = 39;</code>
     */
    protected $pg_id = '';
    /**
     * Generated from protobuf field <code>string pg_provider = 40;</code>
     */
    protected $pg_provider = '';
    /**
     * Generated from protobuf field <code>string pg_tid = 41;</code>
     */
    protected $pg_tid = '';
    /**
     * Generated from protobuf field <code>string receipt_url = 42;</code>
     */
    protected $receipt_url = '';
    /**
     * Generated from protobuf field <code>int32 started_at = 43;</code>
     */
    protected $started_at = 0;
    /**
     * Generated from protobuf field <code>string status = 44;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>string user_agent = 45;</code>
     */
    protected $user_agent = '';
    /**
     * Generated from protobuf field <code>string vbank_code = 46;</code>
     */
    protected $vbank_code = '';
    /**
     * Generated from protobuf field <code>int32 vbank_date = 47;</code>
     */
    protected $vbank_date = 0;
    /**
     * Generated from protobuf field <code>string vbank_holder = 48;</code>
     */
    protected $vbank_holder = '';
    /**
     * Generated from protobuf field <code>int32 vbank_issued_at = 49;</code>
     */
    protected $vbank_issued_at = 0;
    /**
     * Generated from protobuf field <code>string vbank_name = 50;</code>
     */
    protected $vbank_name = '';
    /**
     * Generated from protobuf field <code>string vbank_num = 51;</code>
     */
    protected $vbank_num = '';
    /**
     * Generated from protobuf field <code>string customer_email = 52;</code>
     */
    protected $customer_email = '';
    /**
     * Generated from protobuf field <code>.basis_v2.Promotion promotion = 53;</code>
     */
    protected $promotion = null;
    /**
     * Generated from protobuf field <code>string npoint_pay_amount = 54;</code>
     */
    protected $npoint_pay_amount = '';
    /**
     * Generated from protobuf field <code>bool sandbox = 55;</code>
     */
    protected $sandbox = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $amount
     *     @type string $apply_num
     *     @type int $bank_code
     *     @type string $bank_name
     *     @type string $buyer_addr
     *     @type string $buyer_email
     *     @type string $buyer_name
     *     @type string $buyer_postcode
     *     @type string $buyer_tel
     *     @type string $cancel_amount
     *     @type \Basis_v2\CancelHistory[]|\Google\Protobuf\Internal\RepeatedField $cancel_history
     *     @type string $cancel_reason
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $cancel_receipt_urls
     *     @type int $cancelled_at
     *     @type string $card_code
     *     @type string $bin_number
     *     @type string $card_name
     *           card issuer
     *     @type string $card_receipe_name
     *     @type string $card_owner_type
     *     @type string $card_brand
     *     @type string $card_credit_type
     *     @type string $card_number
     *     @type int $card_installment
     *     @type int $card_type
     *     @type bool $cash_receipt_issued
     *     @type string $channel
     *     @type string $currency
     *     @type string $custom_data
     *     @type string $card_uid
     *     @type string $customer_uid_usage
     *     @type bool $escrow
     *     @type string $fail_reason
     *     @type int $failed_at
     *     @type string $imp_uid
     *     @type string $merchant_uid
     *     @type string $order_name
     *     @type int $paid_at
     *     @type string $pay_method
     *     @type string $pg_id
     *     @type string $pg_provider
     *     @type string $pg_tid
     *     @type string $receipt_url
     *     @type int $started_at
     *     @type string $status
     *     @type string $user_agent
     *     @type string $vbank_code
     *     @type int $vbank_date
     *     @type string $vbank_holder
     *     @type int $vbank_issued_at
     *     @type string $vbank_name
     *     @type string $vbank_num
     *     @type string $customer_email
     *     @type \Basis_v2\Promotion $promotion
     *     @type string $npoint_pay_amount
     *     @type bool $sandbox
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2\Basis\Basis::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string amount = 1;</code>
     * @return string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>string amount = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkString($var, True);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string apply_num = 2;</code>
     * @return string
     */
    public function getApplyNum()
    {
        return $this->apply_num;
    }

    /**
     * Generated from protobuf field <code>string apply_num = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setApplyNum($var)
    {
        GPBUtil::checkString($var, True);
        $this->apply_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 bank_code = 3;</code>
     * @return int
     */
    public function getBankCode()
    {
        return $this->bank_code;
    }

    /**
     * Generated from protobuf field <code>int32 bank_code = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBankCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->bank_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bank_name = 4;</code>
     * @return string
     */
    public function getBankName()
    {
        return $this->bank_name;
    }

    /**
     * Generated from protobuf field <code>string bank_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBankName($var)
    {
        GPBUtil::checkString($var, True);
        $this->bank_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string buyer_addr = 5;</code>
     * @return string
     */
    public function getBuyerAddr()
    {
        return $this->buyer_addr;
    }

    /**
     * Generated from protobuf field <code>string buyer_addr = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBuyerAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->buyer_addr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string buyer_email = 6;</code>
     * @return string
     */
    public function getBuyerEmail()
    {
        return $this->buyer_email;
    }

    /**
     * Generated from protobuf field <code>string buyer_email = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBuyerEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->buyer_email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string buyer_name = 7;</code>
     * @return string
     */
    public function getBuyerName()
    {
        return $this->buyer_name;
    }

    /**
     * Generated from protobuf field <code>string buyer_name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setBuyerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->buyer_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string buyer_postcode = 8;</code>
     * @return string
     */
    public function getBuyerPostcode()
    {
        return $this->buyer_postcode;
    }

    /**
     * Generated from protobuf field <code>string buyer_postcode = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setBuyerPostcode($var)
    {
        GPBUtil::checkString($var, True);
        $this->buyer_postcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string buyer_tel = 9;</code>
     * @return string
     */
    public function getBuyerTel()
    {
        return $this->buyer_tel;
    }

    /**
     * Generated from protobuf field <code>string buyer_tel = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setBuyerTel($var)
    {
        GPBUtil::checkString($var, True);
        $this->buyer_tel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cancel_amount = 10;</code>
     * @return string
     */
    public function getCancelAmount()
    {
        return $this->cancel_amount;
    }

    /**
     * Generated from protobuf field <code>string cancel_amount = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setCancelAmount($var)
    {
        GPBUtil::checkString($var, True);
        $this->cancel_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .basis_v2.CancelHistory cancel_history = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCancelHistory()
    {
        return $this->cancel_history;
    }

    /**
     * Generated from protobuf field <code>repeated .basis_v2.CancelHistory cancel_history = 11;</code>
     * @param \Basis_v2\CancelHistory[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCancelHistory($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basis_v2\CancelHistory::class);
        $this->cancel_history = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cancel_reason = 12;</code>
     * @return string
     */
    public function getCancelReason()
    {
        return $this->cancel_reason;
    }

    /**
     * Generated from protobuf field <code>string cancel_reason = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setCancelReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->cancel_reason = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string cancel_receipt_urls = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCancelReceiptUrls()
    {
        return $this->cancel_receipt_urls;
    }

    /**
     * Generated from protobuf field <code>repeated string cancel_receipt_urls = 13;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCancelReceiptUrls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->cancel_receipt_urls = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cancelled_at = 14;</code>
     * @return int
     */
    public function getCancelledAt()
    {
        return $this->cancelled_at;
    }

    /**
     * Generated from protobuf field <code>int32 cancelled_at = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setCancelledAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->cancelled_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string card_code = 15;</code>
     * @return string
     */
    public function getCardCode()
    {
        return $this->card_code;
    }

    /**
     * Generated from protobuf field <code>string card_code = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setCardCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->card_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bin_number = 16;</code>
     * @return string
     */
    public function getBinNumber()
    {
        return $this->bin_number;
    }

    /**
     * Generated from protobuf field <code>string bin_number = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setBinNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->bin_number = $var;

        return $this;
    }

    /**
     * card issuer
     *
     * Generated from protobuf field <code>string card_name = 17;</code>
     * @return string
     */
    public function getCardName()
    {
        return $this->card_name;
    }

    /**
     * card issuer
     *
     * Generated from protobuf field <code>string card_name = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setCardName($var)
    {
        GPBUtil::checkString($var, True);
        $this->card_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string card_receipe_name = 18;</code>
     * @return string
     */
    public function getCardReceipeName()
    {
        return $this->card_receipe_name;
    }

    /**
     * Generated from protobuf field <code>string card_receipe_name = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setCardReceipeName($var)
    {
        GPBUtil::checkString($var, True);
        $this->card_receipe_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string card_owner_type = 19;</code>
     * @return string
     */
    public function getCardOwnerType()
    {
        return $this->card_owner_type;
    }

    /**
     * Generated from protobuf field <code>string card_owner_type = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setCardOwnerType($var)
    {
        GPBUtil::checkString($var, True);
        $this->card_owner_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string card_brand = 20;</code>
     * @return string
     */
    public function getCardBrand()
    {
        return $this->card_brand;
    }

    /**
     * Generated from protobuf field <code>string card_brand = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setCardBrand($var)
    {
        GPBUtil::checkString($var, True);
        $this->card_brand = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string card_credit_type = 21;</code>
     * @return string
     */
    public function getCardCreditType()
    {
        return $this->card_credit_type;
    }

    /**
     * Generated from protobuf field <code>string card_credit_type = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setCardCreditType($var)
    {
        GPBUtil::checkString($var, True);
        $this->card_credit_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string card_number = 22;</code>
     * @return string
     */
    public function getCardNumber()
    {
        return $this->card_number;
    }

    /**
     * Generated from protobuf field <code>string card_number = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setCardNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->card_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 card_installment = 23;</code>
     * @return int
     */
    public function getCardInstallment()
    {
        return $this->card_installment;
    }

    /**
     * Generated from protobuf field <code>int32 card_installment = 23;</code>
     * @param int $var
     * @return $this
     */
    public function setCardInstallment($var)
    {
        GPBUtil::checkInt32($var);
        $this->card_installment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 card_type = 24;</code>
     * @return int
     */
    public function getCardType()
    {
        return $this->card_type;
    }

    /**
     * Generated from protobuf field <code>int32 card_type = 24;</code>
     * @param int $var
     * @return $this
     */
    public function setCardType($var)
    {
        GPBUtil::checkInt32($var);
        $this->card_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool cash_receipt_issued = 25;</code>
     * @return bool
     */
    public function getCashReceiptIssued()
    {
        return $this->cash_receipt_issued;
    }

    /**
     * Generated from protobuf field <code>bool cash_receipt_issued = 25;</code>
     * @param bool $var
     * @return $this
     */
    public function setCashReceiptIssued($var)
    {
        GPBUtil::checkBool($var);
        $this->cash_receipt_issued = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string channel = 26;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * Generated from protobuf field <code>string channel = 26;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string currency = 27;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>string currency = 27;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string custom_data = 28;</code>
     * @return string
     */
    public function getCustomData()
    {
        return $this->custom_data;
    }

    /**
     * Generated from protobuf field <code>string custom_data = 28;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomData($var)
    {
        GPBUtil::checkString($var, True);
        $this->custom_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string card_uid = 29;</code>
     * @return string
     */
    public function getCardUid()
    {
        return $this->card_uid;
    }

    /**
     * Generated from protobuf field <code>string card_uid = 29;</code>
     * @param string $var
     * @return $this
     */
    public function setCardUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->card_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string customer_uid_usage = 30;</code>
     * @return string
     */
    public function getCustomerUidUsage()
    {
        return $this->customer_uid_usage;
    }

    /**
     * Generated from protobuf field <code>string customer_uid_usage = 30;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerUidUsage($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_uid_usage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool escrow = 31;</code>
     * @return bool
     */
    public function getEscrow()
    {
        return $this->escrow;
    }

    /**
     * Generated from protobuf field <code>bool escrow = 31;</code>
     * @param bool $var
     * @return $this
     */
    public function setEscrow($var)
    {
        GPBUtil::checkBool($var);
        $this->escrow = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fail_reason = 32;</code>
     * @return string
     */
    public function getFailReason()
    {
        return $this->fail_reason;
    }

    /**
     * Generated from protobuf field <code>string fail_reason = 32;</code>
     * @param string $var
     * @return $this
     */
    public function setFailReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->fail_reason = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 failed_at = 33;</code>
     * @return int
     */
    public function getFailedAt()
    {
        return $this->failed_at;
    }

    /**
     * Generated from protobuf field <code>int32 failed_at = 33;</code>
     * @param int $var
     * @return $this
     */
    public function setFailedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->failed_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string imp_uid = 34;</code>
     * @return string
     */
    public function getImpUid()
    {
        return $this->imp_uid;
    }

    /**
     * Generated from protobuf field <code>string imp_uid = 34;</code>
     * @param string $var
     * @return $this
     */
    public function setImpUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->imp_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string merchant_uid = 35;</code>
     * @return string
     */
    public function getMerchantUid()
    {
        return $this->merchant_uid;
    }

    /**
     * Generated from protobuf field <code>string merchant_uid = 35;</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchant_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_name = 36;</code>
     * @return string
     */
    public function getOrderName()
    {
        return $this->order_name;
    }

    /**
     * Generated from protobuf field <code>string order_name = 36;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderName($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 paid_at = 37;</code>
     * @return int
     */
    public function getPaidAt()
    {
        return $this->paid_at;
    }

    /**
     * Generated from protobuf field <code>int32 paid_at = 37;</code>
     * @param int $var
     * @return $this
     */
    public function setPaidAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->paid_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pay_method = 38;</code>
     * @return string
     */
    public function getPayMethod()
    {
        return $this->pay_method;
    }

    /**
     * Generated from protobuf field <code>string pay_method = 38;</code>
     * @param string $var
     * @return $this
     */
    public function setPayMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->pay_method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pg_id = 39;</code>
     * @return string
     */
    public function getPgId()
    {
        return $this->pg_id;
    }

    /**
     * Generated from protobuf field <code>string pg_id = 39;</code>
     * @param string $var
     * @return $this
     */
    public function setPgId($var)
    {
        GPBUtil::checkString($var, True);
        $this->pg_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pg_provider = 40;</code>
     * @return string
     */
    public function getPgProvider()
    {
        return $this->pg_provider;
    }

    /**
     * Generated from protobuf field <code>string pg_provider = 40;</code>
     * @param string $var
     * @return $this
     */
    public function setPgProvider($var)
    {
        GPBUtil::checkString($var, True);
        $this->pg_provider = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pg_tid = 41;</code>
     * @return string
     */
    public function getPgTid()
    {
        return $this->pg_tid;
    }

    /**
     * Generated from protobuf field <code>string pg_tid = 41;</code>
     * @param string $var
     * @return $this
     */
    public function setPgTid($var)
    {
        GPBUtil::checkString($var, True);
        $this->pg_tid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string receipt_url = 42;</code>
     * @return string
     */
    public function getReceiptUrl()
    {
        return $this->receipt_url;
    }

    /**
     * Generated from protobuf field <code>string receipt_url = 42;</code>
     * @param string $var
     * @return $this
     */
    public function setReceiptUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->receipt_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 started_at = 43;</code>
     * @return int
     */
    public function getStartedAt()
    {
        return $this->started_at;
    }

    /**
     * Generated from protobuf field <code>int32 started_at = 43;</code>
     * @param int $var
     * @return $this
     */
    public function setStartedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->started_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 44;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 44;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_agent = 45;</code>
     * @return string
     */
    public function getUserAgent()
    {
        return $this->user_agent;
    }

    /**
     * Generated from protobuf field <code>string user_agent = 45;</code>
     * @param string $var
     * @return $this
     */
    public function setUserAgent($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_agent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vbank_code = 46;</code>
     * @return string
     */
    public function getVbankCode()
    {
        return $this->vbank_code;
    }

    /**
     * Generated from protobuf field <code>string vbank_code = 46;</code>
     * @param string $var
     * @return $this
     */
    public function setVbankCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->vbank_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 vbank_date = 47;</code>
     * @return int
     */
    public function getVbankDate()
    {
        return $this->vbank_date;
    }

    /**
     * Generated from protobuf field <code>int32 vbank_date = 47;</code>
     * @param int $var
     * @return $this
     */
    public function setVbankDate($var)
    {
        GPBUtil::checkInt32($var);
        $this->vbank_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vbank_holder = 48;</code>
     * @return string
     */
    public function getVbankHolder()
    {
        return $this->vbank_holder;
    }

    /**
     * Generated from protobuf field <code>string vbank_holder = 48;</code>
     * @param string $var
     * @return $this
     */
    public function setVbankHolder($var)
    {
        GPBUtil::checkString($var, True);
        $this->vbank_holder = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 vbank_issued_at = 49;</code>
     * @return int
     */
    public function getVbankIssuedAt()
    {
        return $this->vbank_issued_at;
    }

    /**
     * Generated from protobuf field <code>int32 vbank_issued_at = 49;</code>
     * @param int $var
     * @return $this
     */
    public function setVbankIssuedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->vbank_issued_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vbank_name = 50;</code>
     * @return string
     */
    public function getVbankName()
    {
        return $this->vbank_name;
    }

    /**
     * Generated from protobuf field <code>string vbank_name = 50;</code>
     * @param string $var
     * @return $this
     */
    public function setVbankName($var)
    {
        GPBUtil::checkString($var, True);
        $this->vbank_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vbank_num = 51;</code>
     * @return string
     */
    public function getVbankNum()
    {
        return $this->vbank_num;
    }

    /**
     * Generated from protobuf field <code>string vbank_num = 51;</code>
     * @param string $var
     * @return $this
     */
    public function setVbankNum($var)
    {
        GPBUtil::checkString($var, True);
        $this->vbank_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string customer_email = 52;</code>
     * @return string
     */
    public function getCustomerEmail()
    {
        return $this->customer_email;
    }

    /**
     * Generated from protobuf field <code>string customer_email = 52;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.basis_v2.Promotion promotion = 53;</code>
     * @return \Basis_v2\Promotion|null
     */
    public function getPromotion()
    {
        return $this->promotion;
    }

    public function hasPromotion()
    {
        return isset($this->promotion);
    }

    public function clearPromotion()
    {
        unset($this->promotion);
    }

    /**
     * Generated from protobuf field <code>.basis_v2.Promotion promotion = 53;</code>
     * @param \Basis_v2\Promotion $var
     * @return $this
     */
    public function setPromotion($var)
    {
        GPBUtil::checkMessage($var, \Basis_v2\Promotion::class);
        $this->promotion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string npoint_pay_amount = 54;</code>
     * @return string
     */
    public function getNpointPayAmount()
    {
        return $this->npoint_pay_amount;
    }

    /**
     * Generated from protobuf field <code>string npoint_pay_amount = 54;</code>
     * @param string $var
     * @return $this
     */
    public function setNpointPayAmount($var)
    {
        GPBUtil::checkString($var, True);
        $this->npoint_pay_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool sandbox = 55;</code>
     * @return bool
     */
    public function getSandbox()
    {
        return $this->sandbox;
    }

    /**
     * Generated from protobuf field <code>bool sandbox = 55;</code>
     * @param bool $var
     * @return $this
     */
    public function setSandbox($var)
    {
        GPBUtil::checkBool($var);
        $this->sandbox = $var;

        return $this;
    }

}

