// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package authenticate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AuthenticateServiceClient is the client API for AuthenticateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthenticateServiceClient interface {
	TokenRPC(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	RegisterPubKeyRPC(ctx context.Context, in *PubKeyRegisterRequest, opts ...grpc.CallOption) (*PubKeyRegisterResponse, error)
}

type authenticateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticateServiceClient(cc grpc.ClientConnInterface) AuthenticateServiceClient {
	return &authenticateServiceClient{cc}
}

func (c *authenticateServiceClient) TokenRPC(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, "/authenticate_v2.AuthenticateService/TokenRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticateServiceClient) RegisterPubKeyRPC(ctx context.Context, in *PubKeyRegisterRequest, opts ...grpc.CallOption) (*PubKeyRegisterResponse, error) {
	out := new(PubKeyRegisterResponse)
	err := c.cc.Invoke(ctx, "/authenticate_v2.AuthenticateService/RegisterPubKeyRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticateServiceServer is the server API for AuthenticateService service.
// All implementations must embed UnimplementedAuthenticateServiceServer
// for forward compatibility
type AuthenticateServiceServer interface {
	TokenRPC(context.Context, *TokenRequest) (*TokenResponse, error)
	RegisterPubKeyRPC(context.Context, *PubKeyRegisterRequest) (*PubKeyRegisterResponse, error)
	mustEmbedUnimplementedAuthenticateServiceServer()
}

// UnimplementedAuthenticateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthenticateServiceServer struct {
}

func (UnimplementedAuthenticateServiceServer) TokenRPC(context.Context, *TokenRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenRPC not implemented")
}
func (UnimplementedAuthenticateServiceServer) RegisterPubKeyRPC(context.Context, *PubKeyRegisterRequest) (*PubKeyRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterPubKeyRPC not implemented")
}
func (UnimplementedAuthenticateServiceServer) mustEmbedUnimplementedAuthenticateServiceServer() {}

// UnsafeAuthenticateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthenticateServiceServer will
// result in compilation errors.
type UnsafeAuthenticateServiceServer interface {
	mustEmbedUnimplementedAuthenticateServiceServer()
}

func RegisterAuthenticateServiceServer(s grpc.ServiceRegistrar, srv AuthenticateServiceServer) {
	s.RegisterService(&_AuthenticateService_serviceDesc, srv)
}

func _AuthenticateService_TokenRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticateServiceServer).TokenRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authenticate_v2.AuthenticateService/TokenRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticateServiceServer).TokenRPC(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticateService_RegisterPubKeyRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubKeyRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticateServiceServer).RegisterPubKeyRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authenticate_v2.AuthenticateService/RegisterPubKeyRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticateServiceServer).RegisterPubKeyRPC(ctx, req.(*PubKeyRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authenticate_v2.AuthenticateService",
	HandlerType: (*AuthenticateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TokenRPC",
			Handler:    _AuthenticateService_TokenRPC_Handler,
		},
		{
			MethodName: "RegisterPubKeyRPC",
			Handler:    _AuthenticateService_RegisterPubKeyRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v2/authenticate/authenticate.proto",
}
