// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: v1/certification/certification.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace V1.Certification {

  /// <summary>Holder for reflection information generated from v1/certification/certification.proto</summary>
  public static partial class CertificationReflection {

    #region Descriptor
    /// <summary>File descriptor for v1/certification/certification.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CertificationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiR2MS9jZXJ0aWZpY2F0aW9uL2NlcnRpZmljYXRpb24ucHJvdG8SDWNlcnRp",
            "ZmljYXRpb24aHGdvb2dsZS9hcGkvYW5ub3RhdGlvbnMucHJvdG8iJwoUQ2Vy",
            "dGlmaWNhdGlvblJlcXVlc3QSDwoHaW1wX3VpZBgBIAEoCSJmChVDZXJ0aWZp",
            "Y2F0aW9uUmVzcG9uc2USDAoEY29kZRgBIAEoBRIPCgdtZXNzYWdlGAIgASgJ",
            "Ei4KCHJlc3BvbnNlGAMgASgLMhwuY2VydGlmaWNhdGlvbi5DZXJ0aWZpY2F0",
            "aW9uIrICCg1DZXJ0aWZpY2F0aW9uEg8KB2ltcF91aWQYASABKAkSFAoMbWVy",
            "Y2hhbnRfdWlkGAIgASgJEg4KBnBnX3RpZBgDIAEoCRITCgtwZ19wcm92aWRl",
            "chgEIAEoCRIMCgRuYW1lGAUgASgJEg4KBmdlbmRlchgGIAEoCRINCgViaXJ0",
            "aBgHIAEoBRIQCghiaXJ0aGRheRgIIAEoCRIRCglmb3JlaWduZXIYCSABKAgS",
            "DQoFcGhvbmUYCiABKAkSDwoHY2FycmllchgLIAEoCRIRCgljZXJ0aWZpZWQY",
            "DCABKAgSFAoMY2VydGlmaWVkX2F0GA0gASgFEhIKCnVuaXF1ZV9rZXkYDiAB",
            "KAkSFgoOdW5pcXVlX2luX3NpdGUYDyABKAkSDgoGb3JpZ2luGBAgASgJMsUC",
            "ChRDZXJ0aWZpY2F0aW9uU2VydmljZRKTAQoTQ2VydGlmaWNhdGlvbkdldFJQ",
            "QxIjLmNlcnRpZmljYXRpb24uQ2VydGlmaWNhdGlvblJlcXVlc3QaJC5jZXJ0",
            "aWZpY2F0aW9uLkNlcnRpZmljYXRpb25SZXNwb25zZSIxgtPkkwIrEikvYXBp",
            "L3BheW1lbnRzL3YxL2NlcnRpZmljYXRpb25zL3tpbXBfdWlkfRKWAQoWQ2Vy",
            "dGlmaWNhdGlvbkRlbGV0ZVJQQxIjLmNlcnRpZmljYXRpb24uQ2VydGlmaWNh",
            "dGlvblJlcXVlc3QaJC5jZXJ0aWZpY2F0aW9uLkNlcnRpZmljYXRpb25SZXNw",
            "b25zZSIxgtPkkwIrKikvYXBpL3BheW1lbnRzL3YxL2NlcnRpZmljYXRpb25z",
            "L3tpbXBfdWlkfUJNWjhnaXRodWIuY29tL2lhbXBvcnQvaW50ZXJmYWNlL2dl",
            "bl9zcmMvZ28vdjEvY2VydGlmaWNhdGlvbqoCEFYxLkNlcnRpZmljYXRpb25i",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.Annotations.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::V1.Certification.CertificationRequest), global::V1.Certification.CertificationRequest.Parser, new[]{ "ImpUid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::V1.Certification.CertificationResponse), global::V1.Certification.CertificationResponse.Parser, new[]{ "Code", "Message", "Response" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::V1.Certification.Certification), global::V1.Certification.Certification.Parser, new[]{ "ImpUid", "MerchantUid", "PgTid", "PgProvider", "Name", "Gender", "Birth", "Birthday", "Foreigner", "Phone", "Carrier", "Certified", "CertifiedAt", "UniqueKey", "UniqueInSite", "Origin" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CertificationRequest : pb::IMessage<CertificationRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CertificationRequest> _parser = new pb::MessageParser<CertificationRequest>(() => new CertificationRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CertificationRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::V1.Certification.CertificationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CertificationRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CertificationRequest(CertificationRequest other) : this() {
      impUid_ = other.impUid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CertificationRequest Clone() {
      return new CertificationRequest(this);
    }

    /// <summary>Field number for the "imp_uid" field.</summary>
    public const int ImpUidFieldNumber = 1;
    private string impUid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ImpUid {
      get { return impUid_; }
      set {
        impUid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CertificationRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CertificationRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ImpUid != other.ImpUid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ImpUid.Length != 0) hash ^= ImpUid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ImpUid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ImpUid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ImpUid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ImpUid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ImpUid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ImpUid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CertificationRequest other) {
      if (other == null) {
        return;
      }
      if (other.ImpUid.Length != 0) {
        ImpUid = other.ImpUid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ImpUid = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ImpUid = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CertificationResponse : pb::IMessage<CertificationResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CertificationResponse> _parser = new pb::MessageParser<CertificationResponse>(() => new CertificationResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CertificationResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::V1.Certification.CertificationReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CertificationResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CertificationResponse(CertificationResponse other) : this() {
      code_ = other.code_;
      message_ = other.message_;
      response_ = other.response_ != null ? other.response_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CertificationResponse Clone() {
      return new CertificationResponse(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private int code_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 3;
    private global::V1.Certification.Certification response_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::V1.Certification.Certification Response {
      get { return response_; }
      set {
        response_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CertificationResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CertificationResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Message != other.Message) return false;
      if (!object.Equals(Response, other.Response)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != 0) hash ^= Code.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (response_ != null) hash ^= Response.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Code != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (response_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Response);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Code != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (response_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Response);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Code != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (response_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CertificationResponse other) {
      if (other == null) {
        return;
      }
      if (other.Code != 0) {
        Code = other.Code;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.response_ != null) {
        if (response_ == null) {
          Response = new global::V1.Certification.Certification();
        }
        Response.MergeFrom(other.Response);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 26: {
            if (response_ == null) {
              Response = new global::V1.Certification.Certification();
            }
            input.ReadMessage(Response);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 26: {
            if (response_ == null) {
              Response = new global::V1.Certification.Certification();
            }
            input.ReadMessage(Response);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Certification : pb::IMessage<Certification>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Certification> _parser = new pb::MessageParser<Certification>(() => new Certification());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Certification> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::V1.Certification.CertificationReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Certification() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Certification(Certification other) : this() {
      impUid_ = other.impUid_;
      merchantUid_ = other.merchantUid_;
      pgTid_ = other.pgTid_;
      pgProvider_ = other.pgProvider_;
      name_ = other.name_;
      gender_ = other.gender_;
      birth_ = other.birth_;
      birthday_ = other.birthday_;
      foreigner_ = other.foreigner_;
      phone_ = other.phone_;
      carrier_ = other.carrier_;
      certified_ = other.certified_;
      certifiedAt_ = other.certifiedAt_;
      uniqueKey_ = other.uniqueKey_;
      uniqueInSite_ = other.uniqueInSite_;
      origin_ = other.origin_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Certification Clone() {
      return new Certification(this);
    }

    /// <summary>Field number for the "imp_uid" field.</summary>
    public const int ImpUidFieldNumber = 1;
    private string impUid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ImpUid {
      get { return impUid_; }
      set {
        impUid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "merchant_uid" field.</summary>
    public const int MerchantUidFieldNumber = 2;
    private string merchantUid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MerchantUid {
      get { return merchantUid_; }
      set {
        merchantUid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pg_tid" field.</summary>
    public const int PgTidFieldNumber = 3;
    private string pgTid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PgTid {
      get { return pgTid_; }
      set {
        pgTid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pg_provider" field.</summary>
    public const int PgProviderFieldNumber = 4;
    private string pgProvider_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PgProvider {
      get { return pgProvider_; }
      set {
        pgProvider_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 5;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 6;
    private string gender_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Gender {
      get { return gender_; }
      set {
        gender_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "birth" field.</summary>
    public const int BirthFieldNumber = 7;
    private int birth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Birth {
      get { return birth_; }
      set {
        birth_ = value;
      }
    }

    /// <summary>Field number for the "birthday" field.</summary>
    public const int BirthdayFieldNumber = 8;
    private string birthday_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Birthday {
      get { return birthday_; }
      set {
        birthday_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "foreigner" field.</summary>
    public const int ForeignerFieldNumber = 9;
    private bool foreigner_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Foreigner {
      get { return foreigner_; }
      set {
        foreigner_ = value;
      }
    }

    /// <summary>Field number for the "phone" field.</summary>
    public const int PhoneFieldNumber = 10;
    private string phone_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Phone {
      get { return phone_; }
      set {
        phone_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "carrier" field.</summary>
    public const int CarrierFieldNumber = 11;
    private string carrier_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Carrier {
      get { return carrier_; }
      set {
        carrier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "certified" field.</summary>
    public const int CertifiedFieldNumber = 12;
    private bool certified_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Certified {
      get { return certified_; }
      set {
        certified_ = value;
      }
    }

    /// <summary>Field number for the "certified_at" field.</summary>
    public const int CertifiedAtFieldNumber = 13;
    private int certifiedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CertifiedAt {
      get { return certifiedAt_; }
      set {
        certifiedAt_ = value;
      }
    }

    /// <summary>Field number for the "unique_key" field.</summary>
    public const int UniqueKeyFieldNumber = 14;
    private string uniqueKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UniqueKey {
      get { return uniqueKey_; }
      set {
        uniqueKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "unique_in_site" field.</summary>
    public const int UniqueInSiteFieldNumber = 15;
    private string uniqueInSite_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UniqueInSite {
      get { return uniqueInSite_; }
      set {
        uniqueInSite_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "origin" field.</summary>
    public const int OriginFieldNumber = 16;
    private string origin_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Origin {
      get { return origin_; }
      set {
        origin_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Certification);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Certification other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ImpUid != other.ImpUid) return false;
      if (MerchantUid != other.MerchantUid) return false;
      if (PgTid != other.PgTid) return false;
      if (PgProvider != other.PgProvider) return false;
      if (Name != other.Name) return false;
      if (Gender != other.Gender) return false;
      if (Birth != other.Birth) return false;
      if (Birthday != other.Birthday) return false;
      if (Foreigner != other.Foreigner) return false;
      if (Phone != other.Phone) return false;
      if (Carrier != other.Carrier) return false;
      if (Certified != other.Certified) return false;
      if (CertifiedAt != other.CertifiedAt) return false;
      if (UniqueKey != other.UniqueKey) return false;
      if (UniqueInSite != other.UniqueInSite) return false;
      if (Origin != other.Origin) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ImpUid.Length != 0) hash ^= ImpUid.GetHashCode();
      if (MerchantUid.Length != 0) hash ^= MerchantUid.GetHashCode();
      if (PgTid.Length != 0) hash ^= PgTid.GetHashCode();
      if (PgProvider.Length != 0) hash ^= PgProvider.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Gender.Length != 0) hash ^= Gender.GetHashCode();
      if (Birth != 0) hash ^= Birth.GetHashCode();
      if (Birthday.Length != 0) hash ^= Birthday.GetHashCode();
      if (Foreigner != false) hash ^= Foreigner.GetHashCode();
      if (Phone.Length != 0) hash ^= Phone.GetHashCode();
      if (Carrier.Length != 0) hash ^= Carrier.GetHashCode();
      if (Certified != false) hash ^= Certified.GetHashCode();
      if (CertifiedAt != 0) hash ^= CertifiedAt.GetHashCode();
      if (UniqueKey.Length != 0) hash ^= UniqueKey.GetHashCode();
      if (UniqueInSite.Length != 0) hash ^= UniqueInSite.GetHashCode();
      if (Origin.Length != 0) hash ^= Origin.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ImpUid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ImpUid);
      }
      if (MerchantUid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MerchantUid);
      }
      if (PgTid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PgTid);
      }
      if (PgProvider.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PgProvider);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Name);
      }
      if (Gender.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Gender);
      }
      if (Birth != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Birth);
      }
      if (Birthday.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Birthday);
      }
      if (Foreigner != false) {
        output.WriteRawTag(72);
        output.WriteBool(Foreigner);
      }
      if (Phone.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Phone);
      }
      if (Carrier.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Carrier);
      }
      if (Certified != false) {
        output.WriteRawTag(96);
        output.WriteBool(Certified);
      }
      if (CertifiedAt != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(CertifiedAt);
      }
      if (UniqueKey.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(UniqueKey);
      }
      if (UniqueInSite.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(UniqueInSite);
      }
      if (Origin.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(Origin);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ImpUid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ImpUid);
      }
      if (MerchantUid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MerchantUid);
      }
      if (PgTid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PgTid);
      }
      if (PgProvider.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PgProvider);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Name);
      }
      if (Gender.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Gender);
      }
      if (Birth != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Birth);
      }
      if (Birthday.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Birthday);
      }
      if (Foreigner != false) {
        output.WriteRawTag(72);
        output.WriteBool(Foreigner);
      }
      if (Phone.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Phone);
      }
      if (Carrier.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Carrier);
      }
      if (Certified != false) {
        output.WriteRawTag(96);
        output.WriteBool(Certified);
      }
      if (CertifiedAt != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(CertifiedAt);
      }
      if (UniqueKey.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(UniqueKey);
      }
      if (UniqueInSite.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(UniqueInSite);
      }
      if (Origin.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(Origin);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ImpUid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ImpUid);
      }
      if (MerchantUid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MerchantUid);
      }
      if (PgTid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PgTid);
      }
      if (PgProvider.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PgProvider);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Gender.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Gender);
      }
      if (Birth != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Birth);
      }
      if (Birthday.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Birthday);
      }
      if (Foreigner != false) {
        size += 1 + 1;
      }
      if (Phone.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Phone);
      }
      if (Carrier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Carrier);
      }
      if (Certified != false) {
        size += 1 + 1;
      }
      if (CertifiedAt != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CertifiedAt);
      }
      if (UniqueKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UniqueKey);
      }
      if (UniqueInSite.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UniqueInSite);
      }
      if (Origin.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Origin);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Certification other) {
      if (other == null) {
        return;
      }
      if (other.ImpUid.Length != 0) {
        ImpUid = other.ImpUid;
      }
      if (other.MerchantUid.Length != 0) {
        MerchantUid = other.MerchantUid;
      }
      if (other.PgTid.Length != 0) {
        PgTid = other.PgTid;
      }
      if (other.PgProvider.Length != 0) {
        PgProvider = other.PgProvider;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Gender.Length != 0) {
        Gender = other.Gender;
      }
      if (other.Birth != 0) {
        Birth = other.Birth;
      }
      if (other.Birthday.Length != 0) {
        Birthday = other.Birthday;
      }
      if (other.Foreigner != false) {
        Foreigner = other.Foreigner;
      }
      if (other.Phone.Length != 0) {
        Phone = other.Phone;
      }
      if (other.Carrier.Length != 0) {
        Carrier = other.Carrier;
      }
      if (other.Certified != false) {
        Certified = other.Certified;
      }
      if (other.CertifiedAt != 0) {
        CertifiedAt = other.CertifiedAt;
      }
      if (other.UniqueKey.Length != 0) {
        UniqueKey = other.UniqueKey;
      }
      if (other.UniqueInSite.Length != 0) {
        UniqueInSite = other.UniqueInSite;
      }
      if (other.Origin.Length != 0) {
        Origin = other.Origin;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ImpUid = input.ReadString();
            break;
          }
          case 18: {
            MerchantUid = input.ReadString();
            break;
          }
          case 26: {
            PgTid = input.ReadString();
            break;
          }
          case 34: {
            PgProvider = input.ReadString();
            break;
          }
          case 42: {
            Name = input.ReadString();
            break;
          }
          case 50: {
            Gender = input.ReadString();
            break;
          }
          case 56: {
            Birth = input.ReadInt32();
            break;
          }
          case 66: {
            Birthday = input.ReadString();
            break;
          }
          case 72: {
            Foreigner = input.ReadBool();
            break;
          }
          case 82: {
            Phone = input.ReadString();
            break;
          }
          case 90: {
            Carrier = input.ReadString();
            break;
          }
          case 96: {
            Certified = input.ReadBool();
            break;
          }
          case 104: {
            CertifiedAt = input.ReadInt32();
            break;
          }
          case 114: {
            UniqueKey = input.ReadString();
            break;
          }
          case 122: {
            UniqueInSite = input.ReadString();
            break;
          }
          case 130: {
            Origin = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ImpUid = input.ReadString();
            break;
          }
          case 18: {
            MerchantUid = input.ReadString();
            break;
          }
          case 26: {
            PgTid = input.ReadString();
            break;
          }
          case 34: {
            PgProvider = input.ReadString();
            break;
          }
          case 42: {
            Name = input.ReadString();
            break;
          }
          case 50: {
            Gender = input.ReadString();
            break;
          }
          case 56: {
            Birth = input.ReadInt32();
            break;
          }
          case 66: {
            Birthday = input.ReadString();
            break;
          }
          case 72: {
            Foreigner = input.ReadBool();
            break;
          }
          case 82: {
            Phone = input.ReadString();
            break;
          }
          case 90: {
            Carrier = input.ReadString();
            break;
          }
          case 96: {
            Certified = input.ReadBool();
            break;
          }
          case 104: {
            CertifiedAt = input.ReadInt32();
            break;
          }
          case 114: {
            UniqueKey = input.ReadString();
            break;
          }
          case 122: {
            UniqueInSite = input.ReadString();
            break;
          }
          case 130: {
            Origin = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
