<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/escrow/escrow.proto

namespace Escrow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>escrow.Logis</code>
 */
class Logis extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string company = 1;</code>
     */
    protected $company = '';
    /**
     * Generated from protobuf field <code>string invoice = 2;</code>
     */
    protected $invoice = '';
    /**
     * Generated from protobuf field <code>int32 sent_at = 3;</code>
     */
    protected $sent_at = 0;
    /**
     * Generated from protobuf field <code>int32 applied_at = 4;</code>
     */
    protected $applied_at = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $company
     *     @type string $invoice
     *     @type int $sent_at
     *     @type int $applied_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V1\Escrow\Escrow::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string company = 1;</code>
     * @return string
     */
    public function getCompany()
    {
        return $this->company;
    }

    /**
     * Generated from protobuf field <code>string company = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCompany($var)
    {
        GPBUtil::checkString($var, True);
        $this->company = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string invoice = 2;</code>
     * @return string
     */
    public function getInvoice()
    {
        return $this->invoice;
    }

    /**
     * Generated from protobuf field <code>string invoice = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setInvoice($var)
    {
        GPBUtil::checkString($var, True);
        $this->invoice = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 sent_at = 3;</code>
     * @return int
     */
    public function getSentAt()
    {
        return $this->sent_at;
    }

    /**
     * Generated from protobuf field <code>int32 sent_at = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSentAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->sent_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 applied_at = 4;</code>
     * @return int
     */
    public function getAppliedAt()
    {
        return $this->applied_at;
    }

    /**
     * Generated from protobuf field <code>int32 applied_at = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAppliedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->applied_at = $var;

        return $this;
    }

}

