<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/authenticate/token.proto

namespace Authenticate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>authenticate.TokenRequest</code>
 */
class TokenRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string imp_key = 1;</code>
     */
    protected $imp_key = '';
    /**
     * Generated from protobuf field <code>string imp_secret = 2;</code>
     */
    protected $imp_secret = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $imp_key
     *     @type string $imp_secret
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V1\Authenticate\Token::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string imp_key = 1;</code>
     * @return string
     */
    public function getImpKey()
    {
        return $this->imp_key;
    }

    /**
     * Generated from protobuf field <code>string imp_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setImpKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->imp_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string imp_secret = 2;</code>
     * @return string
     */
    public function getImpSecret()
    {
        return $this->imp_secret;
    }

    /**
     * Generated from protobuf field <code>string imp_secret = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setImpSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->imp_secret = $var;

        return $this;
    }

}

