<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/authenticate/authenticate.proto

namespace GPBMetadata\V2\Authenticate;

class Authenticate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            '
’
"v2/authenticate/authenticate.protoauthenticate_v2"3
TokenRequest
imp_key (	

imp_secret (	"B
	TokenData
access_token (	

expired_at (
now ("\\
TokenResponse
code (
message (	,
response (2.authenticate_v2.TokenData"N
PubKeyRegisterRequest
imp_key (	

public_key (	
password (	"7
PubKeyRegisterResponse
code (
message (	2¥
AuthenticateServicew

TokenV2RPC.authenticate_v2.TokenRequest.authenticate_v2.TokenResponse"*‚Óä“$"/api/payments/v2/users/gettoken:*”
RegisterPubKeyV2RPC&.authenticate_v2.PubKeyRegisterRequest\'.authenticate_v2.PubKeyRegisterResponse",‚Óä“&"!/api/payments/v2/users/public_key:*BKZ7github.com/iamport/interface/gen_src/go/v2/authenticateªV2.Authenticatebproto3'
        , true);

        static::$is_initialized = true;
    }
}

