<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/supplements/link/link.proto

namespace Link_v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>link_v1.GeneratePaymentURLRequest</code>
 */
class GeneratePaymentURLRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string payment_info = 1;</code>
     */
    protected $payment_info = '';
    /**
     * Generated from protobuf field <code>int64 expired_at = 2;</code>
     */
    protected $expired_at = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $payment_info
     *     @type int|string $expired_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V1\Supplements\Link\Link::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string payment_info = 1;</code>
     * @return string
     */
    public function getPaymentInfo()
    {
        return $this->payment_info;
    }

    /**
     * Generated from protobuf field <code>string payment_info = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 expired_at = 2;</code>
     * @return int|string
     */
    public function getExpiredAt()
    {
        return $this->expired_at;
    }

    /**
     * Generated from protobuf field <code>int64 expired_at = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiredAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->expired_at = $var;

        return $this;
    }

}

